/*

 BKG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\c_code\projects\minigames\frogger\res\tiles\bkg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_map_h_INCLUDE
#define __bkg_map_h_INCLUDE

#define BKG_MAPWidth 32
#define BKG_MAPHeight 32
#define BKG_MAPBank 0

extern const unsigned char BKG_MAP[];

#endif

/* End of BKG_MAP.H */
