/*

 COLLISION_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : collision_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __collision_map_h_INCLUDE
#define __collision_map_h_INCLUDE

#define COLLISION_MAPWidth 32
#define COLLISION_MAPHeight 32
#define COLLISION_MAPBank 0

extern const unsigned char COLLISION_MAP[];

#endif

/* End of COLLISION_MAP.H */
