/*

 FONT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 67

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __font_h_INCLUDE
#define __font_h_INCLUDE

/* Bank of tiles. */
#define FONTBank 0
/* Start of tile array. */
extern const unsigned char FONT[];
#define FONTLen 68

#endif

/* End of FONT.H */
