/*

 FROG_LIVES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char FROG_LIVES[] =
{
  0x00,0x00,0x5D,0x5D,0x7F,0x3E,0x1C,0x1C,
  0x3E,0x1C,0x36,0x36,0x14,0x14,0x77,0x63
};

/* End of FROG_LIVES.C */
