//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frogger_16_H
#define METASPRITE_frogger_16_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frogger_16_TILE_H 16
#define frogger_16_WIDTH 16
#define frogger_16_HEIGHT 16
#define frogger_16_PIVOT_X -8
#define frogger_16_PIVOT_Y -16
#define frogger_16_PIVOT_W 16
#define frogger_16_PIVOT_H 16

BANKREF_EXTERN(frogger_16)

extern const uint16_t frogger_16_palettes[4];
extern const uint8_t frogger_16_tiles[64];

extern const metasprite_t* const frogger_16_metasprites[1];

#endif