//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frogger_H
#define METASPRITE_frogger_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frogger_TILE_H 16
#define frogger_WIDTH 16
#define frogger_HEIGHT 16
#define frogger_PIVOT_X -8
#define frogger_PIVOT_Y -16
#define frogger_PIVOT_W 16
#define frogger_PIVOT_H 16

BANKREF_EXTERN(frogger)

extern const uint16_t frogger_palettes[4];
extern const uint8_t frogger_tiles[64];

extern const metasprite_t* const frogger_metasprites[1];

#endif