/*

 RESET_TIMER.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : C:\c_code\projects\minigames\frogger\res\tiles\bkg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define RESET_TIMERWidth 10
#define RESET_TIMERHeight 1
#define RESET_TIMERBank 0

const unsigned char RESET_TIMER[] =
{
  0x24,0x25,0x25,0x25,0x25,0x25,0x25,0x25,0x25,0x2E
};

/* End of RESET_TIMER.C */
