//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tophat_frog_H
#define METASPRITE_tophat_frog_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tophat_frog_TILE_ORIGIN 0
#define tophat_frog_TILE_H 16
#define tophat_frog_WIDTH 16
#define tophat_frog_HEIGHT 16
#define tophat_frog_TILE_COUNT 4
#define tophat_frog_PIVOT_X -8
#define tophat_frog_PIVOT_Y -16
#define tophat_frog_PIVOT_W 16
#define tophat_frog_PIVOT_H 16

BANKREF_EXTERN(tophat_frog)

extern const palette_color_t tophat_frog_palettes[5];
extern const uint8_t tophat_frog_tiles[64];

extern const metasprite_t* const tophat_frog_metasprites[1];

#endif