/*

 WIN_FROG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : C:\c_code\projects\minigames\frogger\res\tiles\bkg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __win_frog_h_INCLUDE
#define __win_frog_h_INCLUDE

#define WIN_FROGWidth 2
#define WIN_FROGHeight 2
#define WIN_FROGBank 0

extern const unsigned char WIN_FROG[];

#endif

/* End of WIN_FROG.H */
